sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root

#  aliyun:
#    oss:
#      endpoint: "https://oss-ap-northeast-1.aliyuncs.com"
#      bucketName: "javaai-rightzz"
#      region: "ap-northeast-1"

  alioss:
    endpoint: "oss-ap-northeast-1.aliyuncs.com"
    bucket-name: "javaai-rightzz"
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0

  wechat:
    app-id: wx7cea21e894a200d8
    secret: 9147b88cd2c5d7b00b696306091dbc7c